CROSS=/export/home/jxui/iPocketPlus/openwrt/staging_dir/toolchain-arm_v5te_gcc-4.3.3+cs_uClibc-0.9.31_eabi/bin/arm-openwrt-linux-

serial: serial.c 
	${CROSS}gcc -o serial serial.c 


clean:
	rm *.o echoserv serial







